[package]
name = "wos-piano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midly = "0.5.3"

[[bin]]
name = "wos-piano"
path = "main.rs"
